-- Seed existing catalog into Supabase (run AFTER schema.sql)
truncate table public.products, public.categories, public.brands restart identity cascade;

insert into public.brands (slug, name, sort) values
  ('arizona', 'Arizona', 1),
  ('wefaq', 'Al Wefaq', 2),
  ('kitco', 'KITCO', 3),
  ('hero', 'Hero', 4);

insert into public.categories (brand_id, slug, name, cover_url, sort) values
  ((select id from public.brands where slug='arizona'), 'arizona-1', 'Maya Tomato Paste 130g', 'https://atitproject.github.io/alameenpal/brands/arizona-1.jpeg', 1),
  ((select id from public.brands where slug='arizona'), 'arizona-2', 'Coach Jelly Drink 120ml', 'https://atitproject.github.io/alameenpal/brands/arizona-2.jpeg', 2),
  ((select id from public.brands where slug='wefaq'), 'wefaq-1', 'Borgat Gummy Tubs 160g', 'https://atitproject.github.io/alameenpal/brands/wefaq-1.jpeg', 3),
  ((select id from public.brands where slug='wefaq'), 'wefaq-2', 'Borgat 3D Lollipops 40 pcs', 'https://atitproject.github.io/alameenpal/brands/wefaq-2.jpeg', 4),
  ((select id from public.brands where slug='wefaq'), 'wefaq-3', 'Borgat 3D Lollipops 9 pcs', 'https://atitproject.github.io/alameenpal/brands/wefaq-3.jpeg', 5),
  ((select id from public.brands where slug='wefaq'), 'wefaq-4', 'Borgat Gummy 80g', 'https://atitproject.github.io/alameenpal/brands/wefaq-4.jpeg', 6),
  ((select id from public.brands where slug='wefaq'), 'wefaq-5', 'Borgat Marshmallows', 'https://atitproject.github.io/alameenpal/brands/wefaq-5.jpeg', 7),
  ((select id from public.brands where slug='wefaq'), 'wefaq-6', 'Dandormah Ice Pops 90ml', 'https://atitproject.github.io/alameenpal/brands/wefaq-6.jpeg', 8),
  ((select id from public.brands where slug='kitco'), 'kitco-1', 'Kitco Stix Potato Sticks 40g', 'https://atitproject.github.io/alameenpal/brands/kitco-1.jpeg', 9),
  ((select id from public.brands where slug='kitco'), 'kitco-2', 'Kitco Mexita Tortilla Chips', 'https://atitproject.github.io/alameenpal/brands/kitco-2.jpeg', 10),
  ((select id from public.brands where slug='hero'), 'hero-1', 'Vitrac Jam', 'https://atitproject.github.io/alameenpal/brands/hero-1.jpeg', 11),
  ((select id from public.brands where slug='hero'), 'hero-2', 'Hero Jam 350g (Regular & Light)', 'https://atitproject.github.io/alameenpal/brands/hero-2.jpeg', 12),
  ((select id from public.brands where slug='hero'), 'hero-3', 'Peanut Butter & Biscuit Spread 300g', 'https://atitproject.github.io/alameenpal/brands/hero-3.jpeg', 13),
  ((select id from public.brands where slug='hero'), 'hero-4', 'Vitrac Juices (Carton & Glass)', 'https://atitproject.github.io/alameenpal/brands/hero-4.jpeg', 14);

insert into public.products (category_id, name, description, image_url, sort) values
  ((select id from public.categories where slug='arizona-1'), 'Maya Tomato Paste', '100% natural tomato paste in a handy squeeze bottle, 130g.', 'https://atitproject.github.io/alameenpal/brands/arizona-1/p1.jpeg', 1),
  ((select id from public.categories where slug='arizona-1'), 'Maya Tomato Paste – Multipack', 'Value multipack of Maya tomato paste for everyday cooking.', 'https://atitproject.github.io/alameenpal/brands/arizona-1/p2.jpeg', 2),
  ((select id from public.categories where slug='arizona-2'), 'Strawberry Jelly Drink', 'Fruity strawberry-flavoured jelly drink, 120ml.', 'https://atitproject.github.io/alameenpal/brands/arizona-2/p1.png', 1),
  ((select id from public.categories where slug='arizona-2'), 'Orange Jelly Drink', 'Refreshing orange-flavoured jelly drink, 120ml.', 'https://atitproject.github.io/alameenpal/brands/arizona-2/p2.png', 2),
  ((select id from public.categories where slug='arizona-2'), 'Very Berry Jelly Drink', 'Sweet mixed-berry jelly drink, 120ml.', 'https://atitproject.github.io/alameenpal/brands/arizona-2/p3.png', 3),
  ((select id from public.categories where slug='wefaq-1'), 'Sour Strawberry', 'Chewy sour strawberry gummies, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p1.png', 1),
  ((select id from public.categories where slug='wefaq-1'), 'Cakes', 'Colourful celebration-cake shaped gummies, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p2.png', 2),
  ((select id from public.categories where slug='wefaq-1'), 'Glow Stix', 'Space-themed fruity gummy sticks, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p3.png', 3),
  ((select id from public.categories where slug='wefaq-1'), 'Raspberry & Blackberry', 'Berry-flavoured gummies, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p4.png', 4),
  ((select id from public.categories where slug='wefaq-1'), 'Ringlets', 'Fruity gummy rings, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p5.png', 5),
  ((select id from public.categories where slug='wefaq-1'), 'Cola', 'Classic cola-flavoured gummies, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p6.png', 6),
  ((select id from public.categories where slug='wefaq-1'), 'Fruity Wiggles', 'Wiggly assorted-fruit gummies, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p7.png', 7),
  ((select id from public.categories where slug='wefaq-1'), 'Cars', 'Car-shaped fruit gummies, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p8.png', 8),
  ((select id from public.categories where slug='wefaq-1'), 'Peach', 'Soft peach-flavoured gummies, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p9.png', 9),
  ((select id from public.categories where slug='wefaq-1'), 'Bumble Bear', 'Fruit-flavoured gummy bears, 160g tub.', 'https://atitproject.github.io/alameenpal/brands/wefaq-1/p10.png', 10),
  ((select id from public.categories where slug='wefaq-2'), 'Fruit Shake', '3D fruit-shake flavoured lollipops, 40 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-2/p1.png', 1),
  ((select id from public.categories where slug='wefaq-2'), 'Marra Cola', '3D cola-flavoured lollipops, 40 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-2/p2.png', 2),
  ((select id from public.categories where slug='wefaq-2'), 'Very Berry', '3D mixed-berry lollipops, 40 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-2/p3.png', 3),
  ((select id from public.categories where slug='wefaq-2'), 'Tongue Paint', '3D lollipops that colour your tongue, 40 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-2/p4.png', 4),
  ((select id from public.categories where slug='wefaq-2'), 'Heart Beats', '3D heart-shaped fruit lollipops, 40 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-2/p5.png', 5),
  ((select id from public.categories where slug='wefaq-3'), 'Tongue Paint', '3D lollipops that colour your tongue, 9 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-3/p1.jpeg', 1),
  ((select id from public.categories where slug='wefaq-3'), 'Fruit Shake', '3D fruit-shake flavoured lollipops, 9 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-3/p2.jpeg', 2),
  ((select id from public.categories where slug='wefaq-3'), 'Heart Beats', '3D heart-shaped fruit lollipops, 9 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-3/p3.jpeg', 3),
  ((select id from public.categories where slug='wefaq-3'), 'Marra Cola', '3D cola-flavoured lollipops, 9 pieces.', 'https://atitproject.github.io/alameenpal/brands/wefaq-3/p4.jpeg', 4),
  ((select id from public.categories where slug='wefaq-4'), 'Cars', 'Car-shaped fruit gummies, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p1.png', 1),
  ((select id from public.categories where slug='wefaq-4'), 'Party Mix', 'Assorted party gummy mix, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p2.png', 2),
  ((select id from public.categories where slug='wefaq-4'), 'Hearts', 'Heart-shaped fruit gummies, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p3.png', 3),
  ((select id from public.categories where slug='wefaq-4'), 'Cola', 'Cola-flavoured gummies, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p4.png', 4),
  ((select id from public.categories where slug='wefaq-4'), 'Raspberry & Blackberry', 'Berry-flavoured gummies, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p5.png', 5),
  ((select id from public.categories where slug='wefaq-4'), 'Cakes', 'Celebration-cake shaped gummies, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p6.png', 6),
  ((select id from public.categories where slug='wefaq-4'), 'Bumble Bear', 'Fruit-flavoured gummy bears, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p7.png', 7),
  ((select id from public.categories where slug='wefaq-4'), 'Peach', 'Soft peach-flavoured gummies, 80g.', 'https://atitproject.github.io/alameenpal/brands/wefaq-4/p8.png', 8),
  ((select id from public.categories where slug='wefaq-5'), 'Twiddles – Strawberry Blush', 'Twisted strawberry-blush marshmallows.', 'https://atitproject.github.io/alameenpal/brands/wefaq-5/p1.png', 1),
  ((select id from public.categories where slug='wefaq-5'), 'Watermelon', 'Refreshing watermelon marshmallows.', 'https://atitproject.github.io/alameenpal/brands/wefaq-5/p2.png', 2),
  ((select id from public.categories where slug='wefaq-5'), 'Hearts', 'Vanilla white & strawberry heart marshmallows.', 'https://atitproject.github.io/alameenpal/brands/wefaq-5/p3.png', 3),
  ((select id from public.categories where slug='wefaq-5'), 'Classic – Strawberry & Vanilla', 'Classic vanilla white & strawberry marshmallows.', 'https://atitproject.github.io/alameenpal/brands/wefaq-5/p4.png', 4),
  ((select id from public.categories where slug='wefaq-5'), 'Classic – Vanilla White', 'Classic original vanilla white marshmallows.', 'https://atitproject.github.io/alameenpal/brands/wefaq-5/p5.png', 5),
  ((select id from public.categories where slug='wefaq-5'), 'Mini Puffs & Jumbo Roasters', 'Assorted mini puffs and jumbo roaster marshmallows.', 'https://atitproject.github.io/alameenpal/brands/wefaq-5/p6.png', 6),
  ((select id from public.categories where slug='wefaq-6'), 'Dandormah Ice Pops – Fruittier', 'Assorted fruit-flavoured freeze pops, 90ml.', 'https://atitproject.github.io/alameenpal/brands/wefaq-6/p1.jpeg', 1),
  ((select id from public.categories where slug='kitco-1'), 'Kitco Stix', 'The original crunchy potato sticks in Lightly Salted, Grilled Chicken, Hot & Spicy, Paprika, Tomato Ketchup and Tabasco. 40g cans.', 'https://atitproject.github.io/alameenpal/brands/kitco-1/p1.jpeg', 1),
  ((select id from public.categories where slug='kitco-2'), 'Hot Chilli & Lime', 'Corn tortilla chips with a hot chilli & lime kick.', 'https://atitproject.github.io/alameenpal/brands/kitco-2/p1.jpeg', 1),
  ((select id from public.categories where slug='kitco-2'), 'Sweet & Sour', 'Corn tortilla chips with a sweet & sour flavour.', 'https://atitproject.github.io/alameenpal/brands/kitco-2/p2.jpeg', 2),
  ((select id from public.categories where slug='kitco-2'), 'Sweet Chilli Pepper', 'Corn tortilla chips with sweet chilli pepper.', 'https://atitproject.github.io/alameenpal/brands/kitco-2/p3.jpeg', 3),
  ((select id from public.categories where slug='kitco-2'), 'Nacho Cheese', 'Corn tortilla chips with nacho cheese flavour.', 'https://atitproject.github.io/alameenpal/brands/kitco-2/p4.jpeg', 4),
  ((select id from public.categories where slug='hero-1'), 'Fig Jam', 'Vitrac all-natural fig jam.', 'https://atitproject.github.io/alameenpal/brands/hero-1/p1.jpeg', 1),
  ((select id from public.categories where slug='hero-1'), 'Apricot Jam', 'Vitrac all-natural apricot jam.', 'https://atitproject.github.io/alameenpal/brands/hero-1/p2.jpeg', 2),
  ((select id from public.categories where slug='hero-1'), 'Vitrac Jam Range', 'Vitrac fruit jams in apricot, strawberry and fig.', 'https://atitproject.github.io/alameenpal/brands/hero-1/p3.jpeg', 3),
  ((select id from public.categories where slug='hero-1'), 'Vitrac Jam Trio Pack', 'Value pack of Vitrac strawberry, apricot and fig jams.', 'https://atitproject.github.io/alameenpal/brands/hero-1/p4.jpeg', 4),
  ((select id from public.categories where slug='hero-1'), 'Strawberry Jam', 'Vitrac all-natural strawberry jam.', 'https://atitproject.github.io/alameenpal/brands/hero-1/p5.jpeg', 5),
  ((select id from public.categories where slug='hero-2'), 'Red Cherry Jam', 'Hero all-natural red cherry jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p1.jpeg', 1),
  ((select id from public.categories where slug='hero-2'), 'Orange Jam', 'Hero all-natural orange jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p2.jpeg', 2),
  ((select id from public.categories where slug='hero-2'), 'Blueberry Jam', 'Hero all-natural blueberry jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p3.jpeg', 3),
  ((select id from public.categories where slug='hero-2'), 'Black Cherry Jam', 'Hero all-natural black cherry jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p4.jpeg', 4),
  ((select id from public.categories where slug='hero-2'), 'Mixed Fruits Jam', 'Hero all-natural mixed fruits jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p5.jpeg', 5),
  ((select id from public.categories where slug='hero-2'), 'Apricot Jam', 'Hero all-natural apricot jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p6.jpeg', 6),
  ((select id from public.categories where slug='hero-2'), 'Forest Berry Jam', 'Hero all-natural forest berry jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p7.jpeg', 7),
  ((select id from public.categories where slug='hero-2'), 'Light Jams (Assorted)', 'Hero Light jams with no added sugar: Forest Berry, Black Cherry, Strawberry and Apricot.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p8.jpeg', 8),
  ((select id from public.categories where slug='hero-2'), 'Strawberry Jam', 'Hero all-natural strawberry jam.', 'https://atitproject.github.io/alameenpal/brands/hero-2/p9.jpeg', 9),
  ((select id from public.categories where slug='hero-3'), 'Peanut Butter – Crunchy', 'Hero Delicia crunchy peanut butter, 300g.', 'https://atitproject.github.io/alameenpal/brands/hero-3/p1.jpeg', 1),
  ((select id from public.categories where slug='hero-3'), 'Peanut Butter – Creamy', 'Hero Delicia creamy peanut butter, 300g.', 'https://atitproject.github.io/alameenpal/brands/hero-3/p2.jpeg', 2),
  ((select id from public.categories where slug='hero-3'), 'Peanut Butter – No Added Sugar', 'Hero Delicia peanut butter with no added sugar, 300g.', 'https://atitproject.github.io/alameenpal/brands/hero-3/p3.jpeg', 3),
  ((select id from public.categories where slug='hero-3'), 'Choco Biscuit Spread', 'Hero Delicia chocolate biscuit spread, 300g.', 'https://atitproject.github.io/alameenpal/brands/hero-3/p4.jpeg', 4),
  ((select id from public.categories where slug='hero-3'), 'Cinnamon Biscuit Spread', 'Hero Delicia cinnamon biscuit spread, 300g.', 'https://atitproject.github.io/alameenpal/brands/hero-3/p5.jpeg', 5),
  ((select id from public.categories where slug='hero-3'), 'Vanilla Biscuit Crispy Spread', 'Hero Delicia vanilla biscuit spread with crispy pieces, 300g.', 'https://atitproject.github.io/alameenpal/brands/hero-3/p6.jpeg', 6),
  ((select id from public.categories where slug='hero-4'), 'Pineapple & Orange Nectar', 'Vitrac pineapple & orange nectar – carton.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p1.png', 1),
  ((select id from public.categories where slug='hero-4'), 'Apple Nectar', 'Vitrac apple nectar – carton.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p2.png', 2),
  ((select id from public.categories where slug='hero-4'), 'Mixed Fruit Nectar', 'Vitrac mixed fruit nectar – carton.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p3.png', 3),
  ((select id from public.categories where slug='hero-4'), 'Orange Nectar', 'Vitrac orange nectar – carton.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p4.png', 4),
  ((select id from public.categories where slug='hero-4'), 'Mango Nectar', 'Vitrac mango nectar – carton.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p5.png', 5),
  ((select id from public.categories where slug='hero-4'), 'Pineapple Nectar', 'Vitrac pineapple nectar – carton.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p6.png', 6),
  ((select id from public.categories where slug='hero-4'), 'Guava Nectar', 'Vitrac guava nectar – carton.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p7.png', 7),
  ((select id from public.categories where slug='hero-4'), 'Strawberry Nectar', 'Vitrac strawberry nectar – glass bottle.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p8.png', 8),
  ((select id from public.categories where slug='hero-4'), 'Orange Nectar', 'Vitrac orange nectar – glass bottle.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p9.png', 9),
  ((select id from public.categories where slug='hero-4'), 'Apple Nectar', 'Vitrac apple nectar – glass bottle.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p10.png', 10),
  ((select id from public.categories where slug='hero-4'), 'Mango Nectar', 'Vitrac mango nectar – glass bottle.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p11.png', 11),
  ((select id from public.categories where slug='hero-4'), 'Guava Nectar', 'Vitrac guava nectar – glass bottle.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p12.png', 12),
  ((select id from public.categories where slug='hero-4'), 'Mixed Fruit Nectar', 'Vitrac mixed fruit nectar – glass bottle.', 'https://atitproject.github.io/alameenpal/brands/hero-4/p13.png', 13);
